CREATE USER C##logistica IDENTIFIED BY logistica123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO C##logistica;
GRANT ALL PRIVILEGES TO C##logistica;
GRANT UNLIMITED TABLESPACE TO C##logistica;
